images:
  kraftControllerApplication: docker.io/confluentinc/cp-server:7.5.0
  cpServer: confluentinc/cp-server:7.5.0
  registry: confluentinc/cp-schema-registry:7.5.0
  controlCenter: confluentinc/cp-enterprise-control-center:7.5.0
  init: confluentinc/confluent-init-container:2.7.0
  restProxy: confluentinc/cp-kafka-rest:7.5.1

kraft:
  replicas: 1
  dataVolumeCapacity: 250Mi
  credentialsSecret: kraft-ldap-secret

controlCenter:
  enabled: false
  replicas: 1
  credentialsSecret: control-center-ldap-secret

kafka:
  replicas: 1
  dataVolumeCapacity: 250Mi
  name: kafka-poc

schemaRegistry:
  replicas: 1
  name: schema-registry
  credentialsSecret: schema-registry-ldap-secret

restProxy:
  enabled: false

namespace: kafka-confluent-poc
